helmDefaults:
  createNamespace: false
environments:
  default:
    values:
      - default.values.yaml
  devstand:
    values:
      - devstand.rbk.yaml
  production:
    values:
      - production.rbk.yaml