bases:
  - environments.yaml
---

{{ readFile "hf-templates.yaml" }}

repositories:
- name: rbkmoney
  url: https://rbkmoney.github.io/charts
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts

releases:
{{- if eq .Values.prometheus.enabled true }}
- name: prometheus
  <<: *infra_default
  chart: prometheus-community/kube-prometheus-stack
  namespace: monitoring
  values:
    - namespaceOverride: "monitoring"
{{- end }}
{{- if eq .Values.elk.enabled true }}
- name: logs
  <<: *infra_default
  chart: rbkmoney/elk
{{- end }}
- name: netpolicy
  installed: {{ .Values.cilium.enabled }}
  <<: *infra_default
  chart: rbkmoney/netpolicy
