bases:
  - environments.yaml
---

{{ if .Values.cilium.enabled }}
{{ readFile "hf-templates.yaml" }}
{{ else }}
{{ readFile "hf-templates-cnp-disabled.yaml" }}
{{ end }}

repositories:
- name: stable
  url: https://charts.helm.sh/stable
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: hashicorp
  url: https://helm.releases.hashicorp.com
- name: codecentric
  url: https://codecentric.github.io/helm-charts
- name: rbkmoney
  url: https://rbkmoney.github.io/charts
- name: es
  url: https://helm.elastic.co

# Path to the helmfile state file being processed BEFORE releases in this state file
helmfiles:
  - path: helmfile-infra.yaml

releases:
#External releases
- name: clickhouse-operator
  <<: *default
  chart: rbkmoney/clickhouse-operator
- name: clickhouse
  <<: *default
  chart: rbkmoney/clickhouse
  needs:
  - {{ .Namespace | default "default" }}/clickhouse-operator
  - {{ .Namespace | default "default" }}/kafka
- name: kafka
  <<: *default
  chart: bitnami/kafka
  version: 12.7.3
- name: consul
  <<: *default
  chart: hashicorp/consul
- name: postgres
  <<: *default
  chart: bitnami/postgresql
  version: 9.7.2
  wait: true
- name: vault-cm
  <<: *default
  chart: rbkmoney/raw  
- name: vault
  <<: *default
  chart: hashicorp/vault
  needs:
  - {{ .Namespace | default "default" }}/postgres
  - {{ .Namespace | default "default" }}/vault-cm
  wait: true
- name: keycloak-realms
  <<: *default
  chart: rbkmoney/raw
- name: keycloak
  <<: *default
  chart: codecentric/keycloak
  needs:
  - {{ .Namespace | default "default" }}/postgres
  - {{ .Namespace | default "default" }}/keycloak-realms
  wait: true
- name: deanonimus-es
  <<: *default
  chart: es/elasticsearch
#Rbkmoney processing releases
- name: holmes
  <<: *generic_stateless
- name: riak
  <<: *generic_statefull_json
- name: machinegun
  <<: *generic_stateless_json
  needs:
  - {{ .Namespace | default "default" }}/consul
  - {{ .Namespace | default "default" }}/riak
  - {{ .Namespace | default "default" }}/kafka
- name: bender
  <<: *generic_statefull_json
- name: kds
  <<: *generic_stateless_json
- name: cds
  <<: *generic_stateless_json
  needs:
    - {{ .Namespace | default "default" }}/kds
    - {{ .Namespace | default "default" }}/riak
- name: shumway
  <<: *generic_stateless_json
  needs:
    - {{ .Namespace | default "default" }}/postgres
    - {{ .Namespace | default "default" }}/vault
  wait: true
- name: hooker
  <<: *generic_stateless
  needs:
    - {{ .Namespace | default "default" }}/vault
    - {{ .Namespace | default "default" }}/kafka
    - {{ .Namespace | default "default" }}/hellgate
#    - {{ .Namespace | default "default" }}/fault-detector
- name: dominant
  <<: *generic_stateless_json
  needs:
    - {{ .Namespace | default "default" }}/shumway
    - {{ .Namespace | default "default" }}/machinegun
  wait: true
- name: binbase
  <<: *generic_stateless
- name: proxy-mocketbank
  <<: *generic_stateless_json
  needs:
    - {{ .Namespace | default "default" }}/hellgate
- name: proxy-mocketbank-mpi
  <<: *generic_stateless_json
  needs:
    - {{ .Namespace | default "default" }}/proxy-mocketbank
- name: proxy-mocket-inspector
  <<: *generic_stateless_json
  needs:
    - {{ .Namespace | default "default" }}/hellgate
- name: hellgate
  <<: *generic_stateless_json
  needs:
    - {{ .Namespace | default "default" }}/dominant
    - {{ .Namespace | default "default" }}/machinegun
- name: limiter
  <<: *generic_stateless_json
- name: party-management
  <<: *generic_stateless_json
  needs:
    - {{ .Namespace | default "default" }}/dominant
    - {{ .Namespace | default "default" }}/machinegun
- name: token-keeper
  <<: *generic_stateless_json
  needs:
    - {{ .Namespace | default "default" }}/dominant
- name: capi-pcidss-v2
  <<: *generic_stateless_json
  needs:
    - {{ .Namespace | default "default" }}/keycloak
- name: url-shortener
  <<: *generic_stateless
  needs:
    - {{ .Namespace | default "default" }}/machinegun
    - {{ .Namespace | default "default" }}/keycloak
- name: capi-v2
  <<: *generic_stateless_json
  needs:
    - {{ .Namespace | default "default" }}/keycloak
    - {{ .Namespace | default "default" }}/dominant
- name: wapi-pcidss-v0
  <<: *generic_stateless_json
  needs:
   - {{ .Namespace | default "default" }}/keycloak
   - {{ .Namespace | default "default" }}/dominant
- name: wapi-v0
  <<: *generic_stateless_json
  needs:
    - {{ .Namespace | default "default" }}/keycloak
    - {{ .Namespace | default "default" }}/dominant
- name: fistful
  <<: *generic_stateless_json
  needs:
    - {{ .Namespace | default "default" }}/dominant
    - {{ .Namespace | default "default" }}/machinegun
- name: fistful-magista
  <<: *generic_stateless
  needs:
    - {{ .Namespace | default "default" }}/vault
- name: payform
  <<: *generic_stateless
- name: test-transaction
  <<: *generic_stateless
  needs:
    - {{ .Namespace | default "default" }}/shumway
    - {{ .Namespace | default "default" }}/dominant
    - {{ .Namespace | default "default" }}/cds
    - {{ .Namespace | default "default" }}/keycloak
- name: anapi
  <<: *generic_stateless_json
  needs:
    - {{ .Namespace | default "default" }}/keycloak
- name: binapi
  <<: *generic_stateless_json
  needs:
    - {{ .Namespace | default "default" }}/keycloak
- name: controlcenter
  <<: *generic_stateless_json
  needs:
    - {{ .Namespace | default "default" }}/keycloak
- name: weezing
  <<: *generic_stateless_json
  needs:
    - {{ .Namespace | default "default" }}/keycloak
- name: dashboard
  <<: *generic_stateless_json
  needs:
    - {{ .Namespace | default "default" }}/keycloak
- name: analytics
  <<: *generic_stateless
  needs:
    - {{ .Namespace | default "default" }}/postgres
    - {{ .Namespace | default "default" }}/vault
    - {{ .Namespace | default "default" }}/kafka
    - {{ .Namespace | default "default" }}/clickhouse
    - {{ .Namespace | default "default" }}/columbus
    - {{ .Namespace | default "default" }}/dominant
- name: questionary
  <<: *generic_stateless
  needs:
    - {{ .Namespace | default "default" }}/vault
- name: claim-management
  <<: *generic_stateless
  needs:
    - {{ .Namespace | default "default" }}/postgres
    - {{ .Namespace | default "default" }}/vault
    - {{ .Namespace | default "default" }}/kafka
    - {{ .Namespace | default "default" }}/hellgate
    - {{ .Namespace | default "default" }}/party-management
- name: questionary-aggr-proxy
  <<: *generic_stateless
- name: magista
  <<: *generic_stateless
  needs:
    - {{ .Namespace | default "default" }}/vault
    - {{ .Namespace | default "default" }}/kafka
#    - {{ .Namespace | default "default" }}/columbus
    - {{ .Namespace | default "default" }}/hellgate
#    - {{ .Namespace | default "default" }}/payouter-
- name: xrates
  <<: *generic_stateless
  installed: false
  needs:
    - {{ .Namespace | default "default" }}/vault
    - {{ .Namespace | default "default" }}/machinegun
- name: payouter
  <<: *generic_stateless_json
  needs:
    - {{ .Namespace | default "default" }}/vault
- name: columbus
  <<: *generic_stateless_json
  needs:
    - {{ .Namespace | default "default" }}/columbus-pg
- name: columbus-pg
  <<: *generic_stateless_json
- name: dark-api
  <<: *generic_stateless
  needs:
    - {{ .Namespace | default "default" }}/magista
    - {{ .Namespace | default "default" }}/claim-management
    - {{ .Namespace | default "default" }}/messages
    - {{ .Namespace | default "default" }}/questionary-aggr-proxy
    - {{ .Namespace | default "default" }}/questionary
#    - {{ .Namespace | default "default" }}/file-storage
    - {{ .Namespace | default "default" }}/hellgate
    - {{ .Namespace | default "default" }}/dominant
- name: wb-list-manager
  installed: false
  <<: *generic_stateless_json
- name: fraudbusters-mgmt
  installed: false
  <<: *generic_stateless_json
  needs:
  - {{ .Namespace | default "default" }}/vault
  - {{ .Namespace | default "default" }}/kafka
  - {{ .Namespace | default "default" }}/fraudbusters
  - {{ .Namespace | default "default" }}/fraudbusters-notificator
- name: fraudbusters
  installed: false  
  <<: *generic_stateless_json
  needs:
  - {{ .Namespace | default "default" }}/wb-list-manager
  - {{ .Namespace | default "default" }}/columbus
- name: fraudbusters-warehouse
  installed: false
  <<: *generic_stateless_json
  needs:
    - {{ .Namespace | default "default" }}/clickhouse
- name: fraudbusters-notificator
  installed: false
  <<: *generic_stateless_json
  needs:
    - {{ .Namespace | default "default" }}/vault
    - {{ .Namespace | default "default" }}/fraudbusters-warehouse
- name: deanonimus
  <<: *generic_stateless_json
  needs:
  - {{ .Namespace | default "default" }}/deanonimus-es
- name: messages
  <<: *generic_stateless_json
  needs:
  - {{ .Namespace | default "default" }}/postgres
  - {{ .Namespace | default "default" }}/vault
- name: papi
  <<: *generic_stateless_json
  needs:
  - {{ .Namespace | default "default" }}/dominant
  - {{ .Namespace | default "default" }}/magista
  - {{ .Namespace | default "default" }}/hellgate
- name: reporter
  <<: *generic_stateless
  needs:
    - {{ .Namespace | default "default" }}/vault
    - {{ .Namespace | default "default" }}/kafka
    - {{ .Namespace | default "default" }}/hellgate
    - {{ .Namespace | default "default" }}/magista
    - {{ .Namespace | default "default" }}/dominant
- name: bouncer
  <<: *generic_stateless_json
- name: bouncer-policies
  <<: *generic_stateless_json
- name: org-manager
  <<: *generic_stateless_json
  needs:
    - {{ .Namespace | default "default" }}/postgres
    - {{ .Namespace | default "default" }}/keycloak
- name: claim-api
  <<: *generic_stateless_json
  needs:
    - {{ .Namespace | default "default" }}/keycloak
    - {{ .Namespace | default "default" }}/party-management
    - {{ .Namespace | default "default" }}/bouncer
    - {{ .Namespace | default "default" }}/claim-management
- name: file-storage
  <<: *generic_stateless
- name: dudoser
  <<: *generic_stateless_json
  needs:
    - {{ .Namespace | default "default" }}/hellgate
    - {{ .Namespace | default "default" }}/kafka
- name: fraudbusters-ui
  <<: *generic_stateless_json
  needs:
    - {{ .Namespace | default "default" }}/keycloak
