---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: default.consul
  namespace: default
specs:
  - endpointSelector:
      matchLabels:
        k8s:selector.cilium.rbkmoney/release: consul
    egress:
    - toEndpoints:
        - matchLabels:
            k8s:selector.cilium.rbkmoney/release: machinegun
  - endpointSelector:
      matchLabels:
        k8s:selector.cilium.rbkmoney/release: machinegun
    ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:selector.cilium.rbkmoney/release: consul
