---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "keycloak-postgres"
  namespace: default
specs:
  - endpointSelector:
      matchLabels:
        k8s:selector.cilium.rbkmoney/release: keycloak
    egress:
    - toEndpoints:
      - matchLabels:
          k8s:selector.cilium.rbkmoney/release: postgres
      toPorts:
      - ports:
        - protocol: TCP
          port: "5432"
  - endpointSelector:
      matchLabels:
        k8s:selector.cilium.rbkmoney/release: postgres
    ingress:
    - fromEndpoints:
      - matchLabels:
          k8s:selector.cilium.rbkmoney/release: keycloak
      toPorts:
      - ports:
        - protocol: TCP
          port: "5432"
