---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-kafka-brokers"
  namespace: default
spec:
  endpointSelector:
    matchLabels:
      k8s:selector.cilium.rbkmoney/release: kafka
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:selector.cilium.rbkmoney/release: kafka
    toPorts:
    - ports:
      - port: "9092"
        protocol: TCP
  egress:
  - toEndpoints:
    - matchLabels:
        k8s:selector.cilium.rbkmoney/release: kafka
    toPorts:
    - ports:
      - port: "9092"
        protocol: TCP
