{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "stateless.serviceAccountName" . }}
  labels:
{{ include "stateless.labels" . | indent 4 }}
{{- end -}}
