{
 "title": "Erlang Instance Overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(erlang_vm_process_count, namespace)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(erlang_vm_process_count{namespace=\"$namespace\"}, service)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(erlang_vm_process_count{namespace=\"$namespace\", service=\"$service\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "BEAM Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "erlang_vm_memory_bytes_total{namespace=\"$namespace\", pod=\"$pod\", kind=\"processes\"}",
     "legendFormat": "Processes Memory"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{namespace=\"$namespace\", pod=\"$pod\", usage=\"atom\"}",
     "legendFormat": "Atoms"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{namespace=\"$namespace\", pod=\"$pod\", usage=\"binary\"}",
     "legendFormat": "Binary"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{namespace=\"$namespace\", pod=\"$pod\", usage=\"code\"}",
     "legendFormat": "Code"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{namespace=\"$namespace\", pod=\"$pod\", usage=\"ets\"}",
     "legendFormat": "ETS"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "CPU Limit"
    },
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "irate(erlang_vm_statistics_runtime_milliseconds{namespace=\"$namespace\", pod=\"$pod\"}[$interval]) / on (namespace, pod) irate(erlang_vm_statistics_wallclock_time_milliseconds[$interval])",
     "legendFormat": "BEAM CPU Time"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod=\"$pod\"})",
     "legendFormat": "Pod CPU Time"
    },
    {
     "expr": "max(irate(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\", pod=\"$pod\", container=\"\"}[$interval]) / on (namespace, pod, container, node, service) irate(container_cpu_cfs_periods_total[$interval]))",
     "legendFormat": "CPU Throttling"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(erlang_vm_statistics_context_switches{namespace=\"$namespace\", pod=\"$pod\"}[$interval])",
     "legendFormat": "Context Switches"
    },
    {
     "expr": "irate(erlang_vm_statistics_reductions_total{namespace=\"$namespace\", pod=\"$pod\"}[$interval])",
     "legendFormat": "Reductions"
    }
   ]
  },
  {
   "title": "GC",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(erlang_vm_statistics_garbage_collection_number_of_gcs{namespace=\"$namespace\", pod=\"$pod\"}[$interval])",
     "legendFormat": "Number of GCs"
    },
    {
     "expr": "irate(erlang_vm_statistics_garbage_collection_bytes_reclaimed{namespace=\"$namespace\", pod=\"$pod\"}[$interval])",
     "legendFormat": "Bytes Reclaimed"
    }
   ]
  },
  {
   "title": "Pod Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Memory Limit"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Memory Requests"
    },
    {
     "expr": "sum(erlang_vm_memory_system_bytes_total{namespace=\"$namespace\", pod=\"$pod\"})",
     "legendFormat": "BEAM Total"
    },
    {
     "expr": "max(container_memory_rss{namespace=\"$namespace\", pod=\"$pod\", container=\"\"})",
     "legendFormat": "Pod RSS"
    },
    {
     "expr": "max(container_memory_cache{namespace=\"$namespace\", pod=\"$pod\", container=\"\"})",
     "legendFormat": "Pod Cache"
    },
    {
     "expr": "max(container_memory_usage_bytes{namespace=\"$namespace\", pod=\"$pod\", container=\"\"})",
     "legendFormat": "Pod Usage"
    }
   ]
  },
  {
   "title": "IO",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(erlang_vm_statistics_bytes_received_total{namespace=\"$namespace\", pod=\"$pod\"}[$interval])",
     "legendFormat": "Input"
    },
    {
     "expr": "-irate(erlang_vm_statistics_bytes_output_total{namespace=\"$namespace\", pod=\"$pod\"}[$interval])",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "erlang_vm_process_count{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Processes"
    },
    {
     "expr": "erlang_vm_statistics_run_queues_length_total{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Run Queues Length"
    }
   ]
  }
 ]
}