{
 "title": "TV1-minikube",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "MG warnings and errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "MG {{term @severity.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "@severity.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod.name:machinegun AND (@severity:warning OR @severity:error)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "HG warnings and errors ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "HG {{term @severity.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "@severity.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod.name:hellgate AND (@severity:warning OR @severity:error)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Shumway warnings and errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Shumway {{term @severity.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "@severity.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod.name:shumway AND (@severity:WARN OR @severity:ERROR)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Dominant warnings and errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "dominant {{term @severity.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "@severity.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod.name:dominant AND (@severity:warning OR @severity:error)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Reporter warnings and errors ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "reporter {{term @severity.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "@severity.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod.name:reporter AND (@severity:warning OR @severity:error)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Payouter warnings and errors ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Payouter {{term @severity.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "@severity.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod.name:payouter AND (@severity:warning OR @severity:error)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Out of memory messages",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "HG {{term @severity.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "@severity.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "FACILITY:kern AND (MESSAGE.keyword:/.* Memory cgroup out of memory.*/ OR MESSAGE.keyword:/.*Out of memory: Kill process.*/)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Dudoser warnings and errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "dudoser {{term @severity.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "@severity.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod.name:dudoser AND (@severity:WARN OR @severity:ERROR) AND NOT kubernetes.pod.name:\"cm-dudoser\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Hooker responses",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Request",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod.name:hooker AND logger_name:\"com.rbkmoney.hooker.service.PostSender\" AND message:\"sending message\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Response",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod.name:hooker AND logger_name:\"com.rbkmoney.hooker.service.PostSender\" AND message:\"Response from hook\" AND message:200",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CreatePaymentResource time p95",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "operation_id",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "80",
         "95"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "kubernetes.pod.name:capi AND (operation_id:CreatePaymentResource) AND status:[200 TO 599]",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "operation_id.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "80",
         "95"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "kubernetes.pod.name:capi AND (operation_id:CreatePaymentResource) AND status:[200 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CreateInvoice/CreatePayment time p95",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "operation_id",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "80",
         "95"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "kubernetes.pod.name:capi AND (operation_id:CreateInvoice OR  operation_id:CreatePayment) AND status:[200 TO 299]",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "operation_id.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "80",
         "95"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "kubernetes.pod.name:capi AND (operation_id:CreateInvoice OR  operation_id:CreatePayment) AND status:[200 TO 299]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "HG cache miss by host",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "host.name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "span_id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "rpc.caching_client.service:PartyManagement AND rpc.caching_client.function:Checkout AND rpc.caching_client.event:\"client cache miss\" AND rpc.client.event:\"call service\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "host.name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "span_id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "rpc.caching_client.service:PartyManagement AND rpc.caching_client.function:Checkout AND rpc.caching_client.event:\"client cache hit\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}